build_falter

add single device option

---

packageset/snapshot/backbone.txt
packageset/snapshot/notunnel.txt
packageset/snapshot/tunneldigger.txt

I wrote a collectd plguin for replacing the exec script. It is merged
in the master:
- openwrt/packages#14204
The collectd upstream PR:
- collectd/collectd#3790
Depends on: https://github.com/Freifunk-Spalter/packages/pull/93

packageset: snapshot: add dhcpleases

---

build_falter
patches/json_overview_image_info.py

Finally I made it to sort the current buildbot state into proper commits.
This includes changes, that I hacked into the buildbot manually, to release beta5 faster.

Hack/use falter 19.07 feed

---

packageset/19.07/backbone.txt
packageset/19.07/notunnel.txt
packageset/19.07/tunneldigger.txt
packageset/snapshot/backbone.txt
packageset/snapshot/notunnel.txt
packageset/snapshot/tunneldigger.txt

packageset: use iperf3 instead of iperf

---

build_falter

build_falter: fix typo

---

build_falter
scripts/01-generate_banner.sh
scripts/03-luci-footer.sh

extract the file /etc/freifunk_release directly from the feed
and use the contained information to populate the generated
emedded files

build_falter: get /etc/freifunk_release directly from feed

---

build_falter

This commit applies a uniform coding style to the build_falter
script. I used the programm shfmt with this settings:
```
shfmt -i 4 -w build_falter
```

build_falter: apply uniform identation style

---

README.md

This commit should clarify the context of falter-builter in the
whole falter-project.

README.md: add context description

---

build_falter

This PR contains a bundle minor fixes. Please have a look at the commit descriptions for more details.

Minor fixes

---

packageset/21.02/backbone.txt
packageset/21.02/notunnel.txt
packageset/21.02/tunneldigger.txt

That package provides some handy scripts for working with
olsrd on the cli.

packagesets: add package olsrd-utils

---

README.md
build_falter

This commit introduces the possibility to use a custom imagebuilder.
It fixes #65.

build_falter: add custom imagebuilder

---

README.md
scripts/01-generate_banner.sh

Change the links to freifunk-berlin/falter-* repo

change to new repo location

---

README.md

Should be self explanatory  ;-)

fix typos in the examples

---

README.md
build_falter
lib.bash
scripts/01-generate_banner.sh
scripts/02-favicon.sh
scripts/03-luci-footer.sh
scripts/04-include-falter-feed.sh
scripts/06-luci-base-networkjs.sh

The script got quite big. This commit moves most of the helper
functions to a separate script and introduces better error-handling
on several places.

build_falter: refactoring

---

lib.bash

zram can improve the performance on 32-mb ram-devices.

build_falter: add zram on 32mb-devices

---

build_falter
lib.bash

This includes a nice banner done by @kls0e.
Fixes #102

build_falter: include banner artwork

---

packageset/1.2.3/notunnel.txt
packageset/1.2.3/tunneldigger.txt

This adds some minor packages for collectd, which where missing.
In addition, includes ssid-changer into list.

packagelists: tidy up 1.2.3 packages

---

.github/workflows/shellcheck-lint.yml

some work needs to be done to clean up existing scripts before actually merging this github action

add ShellCheck Linter

---

scripts/01-generate_banner.sh
scripts/02-favicon.sh
scripts/03-luci-footer.sh
scripts/04-include-falter-feed.sh
scripts/05-olsrd-init-for-21-02-0.sh
scripts/06-luci-base-networkjs.sh

hook-scripts: fix shellcheck-warnings

---

lib.bash
scripts/03-luci-footer.sh

Not finished until now, we still need to know, where the ucode-template gets placed.

03-luci-footer.sh: adjust for ucode-template

---

.config/yaml-lint.yml
.github/workflows/yaml-lint.yml

Enables yaml-lint for the repo to increase code quality in the future.
Signed-off-by: Tobias Schwarz <info@tobias-schwarz.com>

workflows: enable yaml-lint for the repo

---

build_falter
packageset/1.2.3/notunnel.txt
packageset/1.2.3/tunneldigger.txt
packageset/1.3.0/notunnel.txt
packageset/1.3.0/tunneldigger.txt
packageset/snapshot/notunnel.txt
packageset/snapshot/tunneldigger.txt

This commit adds service registrar for upcoming 1.2.3, 1.3.0-snapshot and snapshot-builds

packagelists: add service registrar

---

build_falter

The 21.02.6 build finally finished \o/

build: bump 1.2.3 imagebuilder to 21.02.6

---

build_falter

21.02.7 is still building, 22.03.5 is complete

build: bump imagebuilders to 22.03.5 and 21.02.7

---

build/build.sh

Skip individual device build errors and save the log into a `faillogs/` directory alongside the successful image files.

build: save faillogs for devices that fail to build

---

build/build.sh

As discussed in https://github.com/freifunk-berlin/meta/issues/91

build.sh: remove unused variable

---

packageset/1.5.0/backbone.txt
packageset/1.5.0/notunnel.txt
packageset/1.5.0/tunneldigger.txt

build: add packageset for 1.5.0

---

build/build.sh
packageset/1.4.0/notunnel.txt
packageset/1.4.0/tunneldigger.txt

A bunch of 8 MB devices moving from "image too big" to working

build: image size optimizations for 1.4.0 release

---

build/build.sh

This fixes a bunch of ath79 devices (mainly TP-Link and Ubiquiti)

build: more image size optimizations for 1.4.0
