- .gitignore
- build_falter
With this commit, the firmware images from all image-builders
will be stored in a central directory 'firmwares' in the root-
directory.
> build_falter: store images in central directory

- build_falter
The structure of package feed changed. Now, the instruction
sets reside directly und the version-directory.
> build_falter: fix repo-url to new structure

- README.md
- build_falter
This PR enables build_falter to build one specific subtarget only. This solves #7.
> build_falter: enable building specific subtargets only

- build_falter
Due to wrong detection of the profiles contained in the
imagebuilder, some targets did not build. That was the
case for i.e. x86, bcm27xx, and some more.
This commit gives a corrected recipe for fetching those
profiles. It fixes #12.
> build_falter: match profiles correctly

- build_falter
- buildconfig.conf
Defines a variable $VERSIONSTR in buildconfig.conf. That
enables us to mark releases as i.e. beta or rc. Leave
empty for release.
This fixes #15
> build_falter: add version-string

- build_falter
- scripts/03-luci-footer.sh
Using the stored value of FREIFUNK_OPENWRT_BASE, the correct
footer.htm file will be downloaded.  FREIFUNK_OPENWRT_BASE is
found in the freifunk_release file in the falter-common package.
> footer: optimize script to pull the currect luci footer

- README.md
- build_falter
The goal of this PR is, to adopt builter further for the use with buildbot. For that, we need a way to signalise to builter, to generate all three image types at once.
This is a first, rather hacky, draft. Please leave some Comments. :)
> build_falter: enable building all packagesets at once.

- build_falter
The eval-expression introduced in #26 didn't work for stable-releases.
This commit fixes the eval and adjusts the download-url from luci-repo.
> build_falter: fix eval-expression for stable-branches

- build_falter
This commit adds the new OpenWrt-release 19.07.5 into builter-script.
> build_falter: add openwrt-release 19.07.5

- README.md
This commit updates the quickstart example of builter to
the new directory-structure.
In addition, it changes some headlines to right spelling.
This fixes #25.
> README.md: adjust quickstart example

- packageset/19.07/backbone.txt
- packageset/19.07/notunnel.txt
- packageset/19.07/tunneldigger.txt
- packageset/snapshot/backbone.txt
- packageset/snapshot/notunnel.txt
- packageset/snapshot/tunneldigger.txt
In luci-menu, the entry for 'software' was missing. This was
due a missing package for that menu.
This fixes https://github.com/Freifunk-Spalter/packages/issues/99
> packagesets: add luci-app for opkg

- packageset/19.07/backbone.txt
- packageset/19.07/notunnel.txt
- packageset/19.07/tunneldigger.txt
- packageset/snapshot/backbone.txt
- packageset/snapshot/notunnel.txt
- packageset/snapshot/tunneldigger.txt
The removal of dsl-related packages was presumeably introduced
2014 to save space on 4MB-Devices. As Falter does not care for
those, we may readd them.
Have a look at: https://github.com/Freifunk-Spalter/packages/pull/92#issuecomment-744026824
Before merging this, we should have some further discussion on the
standard WAN-Interface (on DSL-Modem or LAN1)
> packagelists: don't remove ppp-related packages

- build_falter
This changes the call to "make image" to include the
option EXTRA_IMAGE_NAME which in the end creates a filename
like "openwrt-19.07.5-freifunk-falter-1.1.0-rc1-BLAHBLAHBLAH.tar.gz"
fixes: #11 
> build_falter: use EXTRA_IMAGE_NAME

- build_falter
- scripts/04-include-falter-feed.sh
The imagsbuilder doesn't include the build-time falter-feed into
the images by itself. This commit enables that, by generating a
customfeeds.conf-file for opkg and include it into the images via
the embedded_files directory.
This commit fixes https://github.com/Freifunk-Spalter/packages/issues/97
> build_falter: include falter-feed into images

- build_falter
This adds the link to the 19.07.6 imagebuilders
> build_falter: add openwrt 19.07.6

- build_falter
When developing, we compile single images a lot. Instead
of loading the whole same imagebuilder from openwrt-servers
everytime, it's much more efficient, to keep those in a cache.
> build_falter: implement caching of imagebuilders

- build_falter
This commit implements a distinction for wave1-devices. They
will get built with non-ct drivers and firmwares instead of the
candelatech ones. This enables this devices to have recent 11s-mesh
connections instead of only deprecated adhoc connections.
This commit addresses: https://github.com/Freifunk-Spalter/packages/issues/43, https://github.com/Freifunk-Spalter/packages/issues/67 and https://github.com/Freifunk-Spalter/packages/issues/27
> build_falter: build wave1-devices with non-ct drivers

- packageset/19.07/backbone.txt
- packageset/19.07/notunnel.txt
- packageset/19.07/tunneldigger.txt
- packageset/snapshot/backbone.txt
- packageset/snapshot/notunnel.txt
- packageset/snapshot/tunneldigger.txt
This commit adds the translation-packages for ffwizard,
wireless settings and policy-routing page to the packagelists.
Thus falter can display them in English and German.
This is related to the Pull-Request https://github.com/Freifunk-Spalter/packages/pull/113.
It helps solving Issue https://github.com/Freifunk-Spalter/packages/issues/110
> packagesets: add transaltion packages

- packageset/19.07/backbone.txt
- packageset/19.07/notunnel.txt
- packageset/19.07/tunneldigger.txt
- packageset/snapshot/backbone.txt
- packageset/snapshot/notunnel.txt
- packageset/snapshot/tunneldigger.txt
replace tcpdump with tcpdump-mini and remove iperf3-ssl
explicitly do not install batctl-tiny since we are installing -full
> packagelists: reduce size of images

- packageset/19.07/backbone.txt
- packageset/19.07/notunnel.txt
- packageset/19.07/tunneldigger.txt
- packageset/snapshot/backbone.txt
- packageset/snapshot/notunnel.txt
- packageset/snapshot/tunneldigger.txt
reorder the batman packages so that batctl-full is listed before
kmod-batman-adv.  Otherwise both batctl-full and batctl-tiny will be
installed.
> packagesets: reorder the batman packages

- README.md
- build_falter
This adds a command line parser to the build-script. It supports
short and long arguments. Currently it doesn't check for plausability.
> build_falter: add command line parser

- packageset/19.07/backbone.txt
- packageset/19.07/notunnel.txt
- packageset/19.07/tunneldigger.txt
- packageset/snapshot/backbone.txt
- packageset/snapshot/notunnel.txt
- packageset/snapshot/tunneldigger.txt
The luci package depends on rpcd-mod-rrdns.  This package is missing
and causing DNS looksups on the "Connections" status page to not work.
Adding the luci package also brings in the additional package "luci-proto-ipv6"
which also is not a bad package to have.
Fixes: https://github.com/Freifunk-Spalter/packages/issues/129
> packagesets: add luci package

- scripts/04-include-falter-feed.sh
As opkg enforces signed packages, it should be okay to download
the packages unencrypted via http.
This PR fixes the issue in recent rc1: opkg wasn't able to download the
packagelists via wget, as there weren't packages installed for that.
> build_falter: change repo to http

- build_falter
The script uses several tools that aren't shipped with standard
distributions. Therefor this script adds a dependency check.
> build_falter: implement dependency check

- packageset/19.07/backbone.txt
- packageset/snapshot/backbone.txt
The following packages are not needed in the backbone images:
luci-i18n-ffwizard-falter-de
luci-i18n-ffwizard-falter-en
luci-i18n-falter-policyrouting-de
luci-i18n-falter-policyrouting-en
simply having these packages cause, at a minimum, the following packages to be installed:
falter-policyrouting
luci-app-falter-policyrouting
luci-app-ffwizard-falter
Fixes: #55
> packagesets: remove unneeded backbone packages

- packageset/19.07/backbone.txt
- packageset/snapshot/backbone.txt
add the falter-berlin-tunneldigger to the backbone images so
that after an upgrade, a backbone node which was either using
tunneldigger for the uplink or for a connection to the bbb-vpn
will continue working
Fixes: #57
> packagesets: add falter-berlin-tunneldigger to backbone

- README.md
- build_falter
- packageset/21.02/backbone.txt
- packageset/21.02/notunnel.txt
- packageset/21.02/tunneldigger.txt
These commits add support for the new openwrt-21.02 branch.  As soon as it is possible to see any content in https://downloads.openwrt.org/releases/21.02-SNAPSHOT/ then this PR will be ready to be merged.
> Support openwrt 21.02

- build_falter
When building for a specific router, we often get easily its
target from the OpenWrt-wikipage. But we need the name of the
routers profile too. This information is embedded in the image-
builder itself.
We can display this inforation comfortably with the new option '-l'.
> build_falter: show router-profiles on request

- build_falter
In #58 I accidentially approved a PR with a minor syntax error.
In bash, there isn't a phrase like 'else if'. Instead, it uses
'elif' keyword for that.
> build_falter: fix else if vs elif

- README.md
- build_falter
In the freifunk_release file of each feed there are variables which
define the OpenWrt-Version the feed is intended for. This commit
introduces changes to use that OpenWrt-Verison mentioned there.
The option `-v` now encodes which falter-version to use. The version
maps directly to the package feed at the buildbot.
This fixes #63.
> build_falter: select openwrt-version via freifunk-release

- build_falter
The structure of the snapshot URLs differs from that of
stable releases and their snapshots. This commit introduces
some code to address that.
Signed-off-by: Maritn Hübner <martin.hubner@web.de>
> build_falter: fix snapshot URL

- patches/workaround-kernel2minor-path-length-limitation.patch
I mixed switches up in #70. Here is a simpler/uglier patch that is easy to understand and does work as expected:
- kernel2minor will not fail
- the output image will be in the right format
Tested with `./build_falter -p packageset/21.02/tunneldigger.txt -v 1.2.0-snapshot -t ipq40xx -s mikrotik -r mikrotik_sxtsq-5-ac
` and made sure that
- there were no error messages from kernel2minor any more and
- that the output (`firmwares/targets/ipq40xx/mikrotik/openwrt-21.02-snapshot-r16065-10a535a90c-freifunk-falter-1.2.0-snapshot-ipq40xx-mikrotik-mikrotik_sxtsq-5-ac-squashfs-sysupgrade.bin`) was in the right format.
> correct workaround-kernel2minor-path-length-limitation.patch

- build_falter
Fail with an error message hinting that the version might be incorrect if the URL cannot be fetched.
I realize #72 recommends to change the command parser however I do not see how to that without hardcoding correct version numbers (bear in mind that we check for `curl` after the command parser).
> Try fetching $FEEDURL to check version - Closes #72

- build_falter
This adds a `patch_if_needed` function to `build_falter` which will check if a patch has already been applied and then apply it only if necessary. See #74.
Tested with:
``` 
./build_falter -p packageset/21.02/tunneldigger.txt -v 1.2.0-snapshot -t ipq40xx -s mikrotik
[...]
patching file scripts/json_overview_image_info.py
patching file include/image-commands.mk
[...]
```
and:
```
./build_falter -p packageset/21.02/tunneldigger.txt -v snapshot -t ipq40xx -s mikrotik
[...]
patching file scripts/json_overview_image_info.py
[...]
````
Note that the second invocation only patches `scripts/json_overview_image_info.py`: this is because the other patch has made it in upstream's `snapshot` version.
> Check whether a patch has already been applied

- build_falter
The script didn't handle the case that the webserver could deliver a prompt
instead of a valid key. Thus it will now check for the distinct comment
line in signify-keys.
In addition option -L gets added, which tells curl to follow redirects
aautomatically.
> build_falter: add check for invalid key and option -L

- build_falter
Some imagebuilder tarballs do not contain a `keys/` directory e.g. `openwrt-imagebuilder-19.07.7-ar71xx-generic.Linux-x86_64.tar.xz` (2021-02-17, `sha1:45492dab1f8e836c4a827d21f9058dbdf700679f`) that gets downloaded when running `./build_falter -p packageset/19.07/notunnel.txt --version 1.1.1 -t ar71xx -s generic -r ubnt-uap-pro`.
This PR creates it as a workaround, with `-p` so that the `mkdir` invocation does not fail should the directory already exist.
Tested with:
- `./build_falter -p packageset/19.07/notunnel.txt --version 1.1.1 -t ar71xx -s generic -r ubnt-uap-pro` (fails withtout patch, works with patch)
- `./build_falter -p packageset/21.02/tunneldigger.txt -v 1.2.0-snapshot -t ipq40xx -s mikrotik -r mikrotik_sxtsq-5-ac` (works with or without patch)
> Ensure keys/ directory exists

- build_falter
If we don't give some parameters like packagesets, the script
never exits. This commit adds some code to avoid that.
> build_falter: check input for beeing complete

- packageset/21.02/backbone.txt
- packageset/21.02/notunnel.txt
- packageset/21.02/tunneldigger.txt
Now that procd handles olsrd[6], the olsrd_watchdog plugin is no
longer needed.
> packageset/20.02: remove olsrd_watchdog from lists

- packageset/21.02/backbone.txt
- packageset/21.02/notunnel.txt
- packageset/21.02/tunneldigger.txt
This PR prepares a new release of the firmware based on the new OpenWrt-Version 21.02.2. It tackles two aspects: more free flash on 8MB-Devices and automatic updates.
> remove batman, add autoupdate

- build_falter
- scripts/04-include-falter-feed.sh
@kls0e spotted an error in the snapshot-images: the opkg
key for the falter feed was not correct. This was due an error
in the script `04-include-falter-feed.sh`, which had an old
URL for the pub-key hardcoded. This is corrected and the URL
is not hardcoded seperately anymore, but get there by cmd-options.
> build_falter: correct buildbot-address

- build_falter
Devices with 8MiB Flash ran out of memory when storing changes
on the configuration. This commit tackles that problem by
automatically removing some not crucial packages, if we detect
a device with 8MiB flash.
This is achieved by loading the OpenWrt Table of Hardware into
a sqlite-db and querying for the flash amount. In the future this
can also be used for detecting 32MiB-RAM devices.
The list of packages that should be removed is defined in a variable
at the tob of the script.
In addition there is a list of routers that should get less packages
even if they have technically more than 8MiB flash. This is useful
for example for UniFi-AC-Mesh, which has two 8MiB-Partitions on a
16MiB-Flash.
Fixes #98. Dates back on a Idea of #34
> build_falter: implement reducing packagelists for 8MiB-Devices

- packageset/snapshot/backbone.txt
- packageset/snapshot/notunnel.txt
- packageset/snapshot/tunneldigger.txt
Since some time firewall4 is the standard instead of abandoned firewall3.
> packagelists: adjust snapshot-lists for fw4

- packageset/1.2.3/backbone.txt
- packageset/1.2.3/notunnel.txt
- packageset/1.2.3/tunneldigger.txt
The builter-script failed on buildbot due to missing package-lists.
This commit fixes that.
Depends on https://github.com/freifunk-berlin/falter-packages/pull/318
> packagelists: add lists for 1.2.3-snapshot

- packageset/1.2.2/backbone.txt
- packageset/1.2.2/notunnel.txt
- packageset/1.2.2/tunneldigger.txt
There were some doubled packages and some minor packages for
collectd missing.
> packagelists: tidy up the lists for 1.2.2

- packageset/1.3.0/backbone.txt
- packageset/1.3.0/notunnel.txt
- packageset/1.3.0/tunneldigger.txt
Add a packagelist for the OpenWrt-22.03-based falter-1.3.0.
> packagelists: add version 1.3.0

- lib.bash
When the database query didn't give a result for flash and
ram size (as it wasn't mentioned in ToH), assure, that we
don't try to use the empty value for the decision on packagelist
modifications
> lib.bash: fix empty field warning

- build_falter
- lib.bash
This commit fixes all remaining shellcheck-warnings. Some
warnings weren't suitable for our needs, so we deactivated them.
Fixes #113
> build_falter, lib.bash: fix shellcheck-warnings

- packageset/snapshot/backbone.txt
- packageset/snapshot/notunnel.txt
- packageset/snapshot/tunneldigger.txt
LuCI removed all english translation packages with commit https://github.com/openwrt/luci/commit/94a1821c3b6ec01817e53a8a01a4cf0b7692ac42 Building the snapshot based FW failed because of this missing packages.
> Remove luci-i18n-*-en from snapshot packagesets

- build_falter
- lib.bash
build_falter will now check for more dependencies. In addition, we
activated errexit in the shell for every bit of the script, except
the imagebuilder. In the imagbuilder there's the possibility that
one single error might break the whole build (for a whole target).
Fixes #116
@pktpls I've runtime tested this only with single-device builds. Before merging, we should have a test-run with multi-device-builds, where one device fails.
> build_falter: better error checking

- .github/workflows/shellcheck-lint.yml
- .github/workflows/yaml-lint.yml
switch to v3 because v2 is deprecated
Signed-off-by: Tobias Schwarz <info@tobias-schwarz.com>
> workflows: update checkout action to v3

- .buildconf/broken-1.2.3-snapshot.txt
- .buildconf/broken-snapshot.txt
- archs38 was removed on snapshot
- the list for 1.2.3-snapshot was copied from snapshot, but needed a few tweeks
> buildconf: update broken targets

- build_falter
- lib.bash
- scripts/03-luci-footer.sh
- scripts/05-inject-freifunk-release.sh
Two little fixes and a big one:
The freifunk_release file in falter-common is not the source of truth
for release branching and versioning anymore. The falter package feeds
are now rolling snapshot feeds just like OpenWrt's.
In this commit we stop reading the freifunk_release file and instead
explicitly define our release branching and versioning. It needs
to be updated whenever a new release branch is created, such as when
openwrt-22.03 was created and openwrt-19.07 removed.
In this commit we also start injecting a new freifunk_release file
into the image.
These two changes change how our releases are defined and started:
Previously we'd commit an updated freifunk_release file to the
falter-packages repo, then build the package feed, the build the
images.
Now all builds are the same and …
> build: explicitly define our branches

- build_falter
When pasting an invalid (misspelled) profile name into builter, it didn't complain properly, but silently stopped working in the imagebuilder. Fixing that, by giving a proper prompt, when trying to build an invalid profile name.
> build_falter: add profile-name validation

- .github/workflows/linter.yml
- build_falter
- lib.bash
See freifunk-berlin/meta#64
Do the following in your local clones of the repository:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
> treewide: rename master branch to main

- build/build.sh
One more little thing - many images are gzip-compressed, e.g. x86/64 and rockchip/armv8
> build: look for *.gz images as well

- build/build.sh
Two problems:
- The script aborted when no other profiles apart from "Default" exist
- The help text was still including the omitted profile
> build: fix omission of Default images

- build/build.sh
- test/vm.sh
We don't need to skip "Default" images, they do build correctly.
But the profile part of their filenames is lowercase, so we need
find's -iname option, instead of -name which is case-sensitive.
Additionally, include Image (kernel images) and *.ubi files in output.
Also, two small VM script fixes from bbb-configs:
- use udhcpc instead of dhclient, which has been deprecated and removed from Alpine
- fix the MTU between host and container
> build: small image selection fixes

- Makefile
- build/generate-autoupdate.sh
- test/extract-vmlinux.sh
Example output for 1.4.0: https://gist.github.com/pktpls/74c98f1bcc62fb14df6e31edac988844
- .devices and .profiles are new and will support the autoupdater dealing with devices changing their target.
- .falter-version has existed before.
- .target has also existed before, and will be removed in the future.
- .image_url is unused and has been removed.
(Sorry I should have just edited the existing generate_autoupdate_json.py - I only noticed later...)
> build: new autoupdate.json generator

- packageset/1.4.0/notunnel.txt
- packageset/1.4.0/tunneldigger.txt
- test/vm.sh
I made some mistakes while creating the 1.4.x branch. The autoupdater, tunneldigger, and ssid-changer packages somehow went missing.
I'll do a full test build, some smaller devices might fail to build because of the slight increase in disk space usage.
If all goes well, I'll click the 1.4.1 release in the night.
> packageset: add missing 1.4.x packages

- test/vm.sh
In Podman with slirp4netns, the DNS server for containers is not on the same IP as the gateway. We can't configure slirp4netns to advertise the DNS server in DHCP replies, so we need to tell OpenWrt about it explicitly.
> vm: make DNS work

- build/build.sh
Lets us specify a mirror URL for 1) downloading the imagebuilder, 2) the falter package feed, 3) the OpenWrt package feeds
> build: add FALTER_MIRROR env var
